# Site settings
title: "On Programming, Computer Graphics <br>and Artificial Intelligence"
author: "Tamilselvan P.R."
description: "A blog about My Musings in Programming, AI, and Technology"
keywords: "Software Engineering, CommonLisp, JavaScript, Python, Shell, Bash, Awk, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I'm a Technical Architect working at JustBuyLive. Here is my Resume <a href='/assets/cv.pdf'>Résumé</a>."
colophon: "© 2016-2017 by Tamilselvan P.R.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://prtamil.github.io"

twitter_username: prtamil
github_username: prtamil
linkedin_username: tamil-selvan-ab46927
facebook_username: prtamil
google-analytics: 

simple_search: http://google.com/search
highlighter: rouge
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
